<?php View::content() ?>
<?php echo Form::open() ?>
<div class="form-group">
	<label>Nombre de Usuario:</label><br>
	<?php echo Form::text("usuario.usuario_nombre","class='form-control'") ?>
</div>
<div class="form-group">
	<label>Contraseña:</label><br>
	<?php echo Form::pass("usuario.usuario_password","class='form-control'") ?>
</div>
<div class="form-group">
	<label>Repetir Contraseña:</label><br>
	<?php echo Form::pass("usuario.usuario_password2","class='form-control'") ?>
</div>
<?php echo Form::submit("Crear","class='btn btn-default'") ?>
<?php echo Form::close() ?>